
apiVersion: v1
kind: Service
metadata:
  labels:
    workflow: actions.github.com-k8s-deploy
    workflowFriendlyName: Django_Application_CICD
  name: django-deployment
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
  type: LoadBalancer
status:
  loadBalancer: {}