apiVersion: v1
kind: ConfigMap
metadata:
  name: djangoapp
data:
  PYTHONUNBUFFERED: "1"
  SQL_SERVER_HOST: "techsckool.database.windows.net"
  SQL_SERVER_PORT: "1433"
  SQL_SERVER_DATABASE: "sqlwebapp"
  SQL_SERVER_USER: "testuser"
  VIJAY: "Saini"

---

apiVersion: v1
kind: Secret
metadata:
  name:  database_password
data:
   SQL_SERVER_PASSWORD: "UEBzc3dvcmQyMDIz"
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: myorgprodacr.azurecr.io/djangoapp:d5732d9886837ddb01df7d87b03ac3a754f8914d
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: djangoapp
        - secretRef:
              name: database_password
        
---

apiVersion: v1
kind: Service
metadata:
  labels:
    workflow: actions.github.com-k8s-deploy
    workflowFriendlyName: Django_Application_CICD
  name: django-deployment
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
  type: LoadBalancer
status:
  loadBalancer: {}